# Generated by Django 6.0.6 on 2026-07-04 16:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_admin_space', models.BooleanField(default=False)),
                ('public_id', models.CharField(max_length=255, unique=True)),
                ('resource_type', models.CharField(default='image', max_length=20)),
                ('format', models.CharField(blank=True, max_length=20)),
                ('secure_url', models.URLField()),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('raw', 'Raw')], default='image', max_length=20)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('is_admin_space', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
