# Generated by Django 6.0.6 on 2026-10-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Manually mark this vehicle as featured on the public homepage.'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('maintenance', 'Maintenance')], db_index=True, default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('dirt-bike', 'Dirt-Bike'), ('suv', 'Suv'), ('electric', 'Electric'), ('scooter', 'Scooter')], max_length=20),
        ),
        migrations.DeleteModel(
            name='VehicleFeature',
        ),
    ]
