# Generated by Django 6.0.6 on 2026-07-04 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediafolder',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Null when is_admin_space=True (admin-owned folder).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediafolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='media_manager.mediafolder'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='media_manager.mediafolder'),
        ),
        migrations.AddIndex(
            model_name='mediafolder',
            index=models.Index(fields=['owner', 'is_admin_space'], name='media_manag_owner_i_aafd03_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediafolder',
            constraint=models.UniqueConstraint(fields=('owner', 'parent', 'name', 'is_admin_space'), name='unique_folder_name_per_parent_per_space'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['owner', 'is_admin_space'], name='media_manag_owner_i_46efce_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['folder'], name='media_manag_folder__801da4_idx'),
        ),
    ]
